# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
if User.all.empty?
  user = CreateAdminService.new.call
  puts 'CREATED ADMIN USER: ' << user.email
end

Category.create([
  {title: 'Design'},
  {title: 'Desenvolvimento'},
  {title: 'Social Media'},
  {title: 'Marketing'},
  {title: 'Business/Executivo'},
  {title: 'Relacionamento com o cliente'},
  {title: 'Suporte'},
  {title: 'Operações'},
  {title: 'Comercial'},
  {title: 'Audiovisual e Fotografia'},
  {title: 'Diversos'}
  ]) if Category.all.count == 0

JobType.create([
  {title: 'Full-time'},
  {title: 'Freelancer'},
  {title: 'Estágio'},
  {title: 'Remoto'}
  ]) if JobType.all.count == 0


Company.create([
  {title:"WorldSense",address:"Rua Guajajaras, 628, sala 212, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/worldsense/",website:"http://www.worldsense.com/"},
  {title:"Mamute Busca Peças",address:"Rua Medeiros n 109 minaslândia",link:"http://www.sanpedrovalley.org/projeto/rua-medeiros-n-109-minaslandia-mamute-busca-pecas/",website:"http://mamutebuscapecas.com.br"},
  {title:"Salpinx",address:"Rua Sergipe, 951, 4º andar, Belo Horizonte (MG)",link:"http://www.sanpedrovalley.org/projeto/rua-sergipe-951-4o-andar-belo-horizonte-mg-salpinx/",website:"http://www.salpinx.com.br"},
  {title:"Master b!",address:"av. João César de Oliveira, 1007, Eldorado, Contagem",link:"http://www.sanpedrovalley.org/projeto/av-joao-cesar-de-oliveira-1007-eldorado-contagem-master-b/",website:"http://masterb.com.br/"},
  {title:"QueroComprar",address:"Avenida Flávio dos Santos, 372 - Floresta, Belo Horizonte - MG, 30150-341",link:"http://www.sanpedrovalley.org/projeto/avenida-flavio-dos-santos-372-floresta-belo-horizonte-mg-30150-341-querocomprar/",website:"http://www.querocomprar.me"},
  {title:"Comunica160",address:"rua Alabandina, 333, Caiçara, Belo Horizonte, Minas Gerais",link:"http://www.sanpedrovalley.org/projeto/rua-alabandina-333-caicara-belo-horizonte-minas-gerais-comunica160/",website:"http://comunica160.com.br/"},
  {title:"Cadê Serviços",address:"Rua Gentil Portugal do Brasil, 55",link:"http://www.sanpedrovalley.org/projeto/rua-gentil-portugal-do-brasil-55-cade-servicos-2/",website:"http://www.cadeservicos.com.br"},
  {title:"Think Beer",address:"Av. Antônio Abrahão Caran, 820, Sala 912",link:"http://www.sanpedrovalley.org/projeto/av-antonio-abrahao-caran-820-sala-912-think-beer/",website:"http://thinkbeer.com.br"},
  {title:"Rakete",address:"Rua Professor Estevão Pinto, 932, bairro Serra - Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/rua-professor-estevao-pinto-932-bairro-serra-belo-horizonte-mg-rakete/",website:"http://www.rakete.com.br"},
  {title:"Carreira EAD",address:"Rua Ari Teixeira da Costa, 254 - Centro - Ribeirão das Neves",link:"http://www.sanpedrovalley.org/projeto/rua-ari-teixeira-da-costa-254-centro-ribeirao-das-neves-carreira-ead/",website:"http://www.carreiraead.com.br"},
  {title:"Dr.Money",address:"Rua Gentil Portugal do Brasil, 55, Camargos, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-gentil-portugal-do-brasil-55-camargos-belo-horizonte-dr-money/",website:"http://www.doutormoneybrasil.com/"},
  {title:"1ª Marcha",address:"Rua Grão Mogol, 662, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-grao-mogol-662-belo-horizonte-1a-marcha/",website:"http://www.1marcha.com.br"},
  {title:"Club Menu",address:"rua desembargador jorge fontana 80 belvedere belo horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-desembargador-jorge-fontana-80-belvedere-belo-horizonte-club-menu/",website:"http://www.clubmenuapp.com"},
  {title:"Onix Creative Agency",address:"Rua Espirito Santo 1204 sala 1407 - Centro - BH",link:"http://www.sanpedrovalley.org/projeto/rua-espirito-santo-1204-sala-1407-centro-bh-mab-comunicacao/"},
  {title:"Aduana Web",address:"Av. Flávio dos Santos, 372, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/av-flavio-dos-santos-372-floresta-mg-aduana-web/",website:"http://www.aduanaweb.com.br"},
  {title:"EuContrato",address:"Rua Juramento, 211 - Pompeia - Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-juramento-211-pompeia-belo-horizonte-eucontrato/",website:"http://www.eucontrato.com"},
  {title:"PLANOS DE ASSESSORIA JURÍDICA A PREÇO FIXO",address:"Avenida Álvares Cabral, 381, conj. 2102/2104",link:"http://www.sanpedrovalley.org/projeto/avenida-alvares-cabral-381-conj-21022104-planos-de-assessoria-juridica-a-preco-fixo/",website:"http://www.thiagoribeiro.adv.br"},
  {title:"Gestor Camaleao",address:"Av. Afonso Pena, 2522 - sl 702/703 - Funcionários - belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/av-afonso-pena-2522-sl-702703-funcionarios-belo-horizonte-gestor-camaleao/",website:"http://www.gestorcamaleao.com.br"},
  {title:"Manus",address:"Rua Boaventura, 1435",link:"http://www.sanpedrovalley.org/projeto/rua-boaventura-1435-manus/",website:"http://projetomanus.wix.com/manus"},
  {title:"Podooy",address:"Rua João Gualberto Filho 541 Sagrada Familia Belo Horizonte Minas Gerais",link:"http://www.sanpedrovalley.org/projeto/rua-joao-gualberto-filho-541-sagrada-familia-belo-horizonte-minas-gerais-podooy-uma-inovadora-rede-baseada-em-localizacao-objetiva-2/",website:"http://www.podooy.com"},
  {title:"Pegada de Lixo",address:"Av Augusto de Lima 233, centro, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/av-augusto-de-lima-233-pegada-de-lixo/",website:"http://www.pegadadelixo.com.br"},
  {title:"outroturismo.com",address:"Rua Augusto Nelson, 64 - Diamantina MG",link:"http://www.sanpedrovalley.org/projeto/rua-augusto-nelson-64-diamantina-mg-outroturismo-com/",website:"http://www.outroturismo.com"},
  {title:"What’s Rel?",address:"Rua Cardeal Vasconcelos Motta, 125",link:"http://www.sanpedrovalley.org/projeto/rua-cardeal-vasconcelos-motta-125-whats-rel/",website:"http://www.whatsrel.com.br"},
  {title:"Lemon",address:"Rua itaúna 86, colégio batista belo horizonte MG 31110-070",link:"http://www.sanpedrovalley.org/projeto/rua-itauna-86-colegio-batista-belo-horizonte-mg-31110-070-lemon/",website:"http://www.lemon360.com.br/"},
  {title:"King Condo",address:"Rua Santa Cruz, 106, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-santa-cruz-106-alto-barroca-king-condo/",website:"https://www.kingcondo.com.br"},
  {title:"Tríaga – escola de gestão e saúde",address:"Av do Contorno, 2905, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/av-do-contorno-2905-belo-horizonte-triaga-escola-de-gestao-e-saude/",website:"http://www.triaga.com.br"},
  {title:"Innovation Labs",address:"Av Alphonsus de Guimarães, 370",link:"http://www.sanpedrovalley.org/projeto/av-alphonsus-de-guimaraes-370-innovation-labs/"},
  {title:"SimSched Direct Block Scheduler",address:"Rua Bela Vista, 230, Padre Eustáquio, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-bela-vista-230-padre-eustaquio-belo-horizonte-simsched-direct-block-scheduler/",website:"http://www.simsched.com"},
  {title:"Landmark",address:"Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/belo-horizonte-landmark/",website:"http://flylandmark.com"},
  {title:"Just Coding – Cursos de Programação de Computadores para Crianças",address:"Rua Kepler, 488, Loja 1, BH, MG",link:"http://www.sanpedrovalley.org/projeto/rua-kepler-488-loja-1-bh-mg-just-coding-cursos-de-programacao-de-computadores-para-criancas/",website:"http://www.justcoding.com.br"},
  {title:"Full tank",address:"Rua Lucena 175, Jardim Europa, Bh",link:"http://www.sanpedrovalley.org/projeto/rua-lucena-175-jardim-europa-bh-full-tank/"},
  {title:"Pic Your Trip",address:"Rua Antonio de Albuquerque, 1185/702",link:"http://www.sanpedrovalley.org/projeto/rua-antonio-de-albuquerque-1185702-pic-your-trip/",website:"http://www.picyourtrip.com.br"},
  {title:"Gopic",address:"Av. Cristóvão Colombo, 454 - sala 301 Savassi Belo Horizonte, Minas Gerais 30140-150 Brazi",link:"http://www.sanpedrovalley.org/projeto/av-cristovao-colombo-454-sala-301-savassi-belo-horizonte-minas-gerais-30140-150-brazi-gopic/",website:"http://gopic.com.br/"},
  {title:"Mood Food",address:"Av Flávio dos Santos, 372, Floresta - Belo Horizonte/MG",link:"http://www.sanpedrovalley.org/projeto/av-flavio-dos-santos-372-floresta-belo-horizontemg-mood-food/",website:"http://www.moodfoodbr.com"},
  {title:"Enterprising UP – Academia de ideias",address:"Rua Leopoldina, 626 - Santo Antônio - Belo Horizonte - Minas Gerais",link:"http://www.sanpedrovalley.org/projeto/rua-leopoldina-626-santo-antonio-belo-horizonte-minas-gerais-enterprising-up-academia-de-ideias/",website:"http://www.enterprisingup.com.br"},
  {title:"Vaga Fácil",address:"Avenida Flávio dos Santos, 372, Floresta, Belo Horizonte.",link:"http://www.sanpedrovalley.org/projeto/avenida-flavio-dos-santos-372-floresta-belo-horizonte-vaga-facil/",website:"http://www.appvagafacil.co/"},
  {title:"Malalai",address:"Rua Flávio dos Santos, 372, Floresta",link:"http://www.sanpedrovalley.org/projeto/rua-flavio-dos-santos-372-floresta-malalai/",website:"http://appmalala.co"},
  {title:"Entenda o cliente",address:"Rua Inconfidentes 1055 Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-inconfidentes-1055-belo-horizonte-entenda-o-cliente/",website:"http://www.entendaocliente.com.br/"},
  {title:"DoEat",address:"Perdigão Malheiros,502, Lj 3",link:"http://www.sanpedrovalley.org/projeto/perdigao-malheiros502-lj-3-doeat/",website:"http://www.doeat.com.br"},
  {title:"Agenda Aqui!",address:"Rua dos Timbiras, 2500, Santo Agostinho - Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-dos-timbiras-2500-santo-agostinho-belo-horizonte-agenda-aqui/",website:"http://www.agendaaqui.com.br/"},
  {title:"Casei Passei",address:"Alameda da serra, 858 /602B - Nova Lima - MG",link:"http://www.sanpedrovalley.org/projeto/alameda-da-serra-858-602b-nova-lima-mg-casei-passei/",website:"http://www.caseipassei.com.br"},
  {title:"NSRV",address:"Av. do Contorno, nº 6283",link:"http://www.sanpedrovalley.org/projeto/av-do-contorno-no-6283-nsrv/"},
  {title:"ÁgilSocial – Intranet Social Corporativa",address:"Rua Ceará 975 - Funcionários",link:"http://www.sanpedrovalley.org/projeto/rua-ceara-975-funcionarios-agilsocial-intranet-social-corporativa/",website:"http://www.agilsocial.com"},
  {title:"Waytracker",address:"Alameda da Serra, 288 - Sala 303 - Vila da Serra Nova Lima",link:"http://www.sanpedrovalley.org/projeto/alameda-da-serra-288-sala-303-vila-da-serra-nova-lima-waytracker/"},
  {title:"NeuroApp",address:"Av. Flávio dos Santos, 372 - Floresta, Belo Horizonte - MG, 31015-150",link:"http://www.sanpedrovalley.org/projeto/av-flavio-dos-santos-372-floresta-belo-horizonte-mg-31015-150-neuroapp/"},
  {title:"i9 Saúde",address:"R. dos Bandolins, 490 - Conj. California, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/r-dos-bandolins-490-conj-california-belo-horizonte-mg-i9-saude/",website:"http://www.i9saude.com.br"},
  {title:"ProPDV – Sistema de Frente de Caixa",address:"Rua Gonzaga, 32 - Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-gonzaga-32-belo-horizonte-propdv-sistema-de-frente-de-caixa/",website:"http://sistemafrentedecaixa.com.br/"},
  {title:"Everycare",address:"Rua dos andes, 341, Prado",link:"http://www.sanpedrovalley.org/projeto/rua-dos-andes-341-prado-everycare/",website:"http://startupthebridge.weebly.com/%20http://everycare.buy-now.co/landingpage"},
  {title:"Ensino Inteligente",address:"Avenida do Contorno, 8000, sala 606 - Santo Agostinho - CEP 30110-932",link:"http://www.sanpedrovalley.org/projeto/avenida-do-contorno-8000-sala-606-santo-agostinho-cep-30110-932-ensino-inteligente/",website:"http://www.eivamosestudar.com.br"},
  {title:"Kcollector",address:"R. Grão Mogol, 662 - Carmo, Belo Horizonte - MG,",link:"http://www.sanpedrovalley.org/projeto/r-grao-mogol-662-carmo-belo-horizonte-mg-kcollector/",website:"http://www.kcollector.com.br"},
  {title:"SuperPetZ",address:"Rua Atalaia, 283 (sala 6), Serrano, Belo Horizonte, Minas Gerais",link:"http://www.sanpedrovalley.org/projeto/rua-atalaia-283-sala-6-serrano-belo-horizonte-minas-gerais-superpetz/",website:"http://superpetz.com.br/"},
  {title:"Next ID",address:"Rua Perdizes, nº 870, Caiçara, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/r-perdizes-870-next-id/",website:"http://www.nextid.com.br"},
  {title:"MED CAR MOBILE",address:"Rua Araras 61 Bairro Concórdia Belo Horizonte MG",link:"http://www.sanpedrovalley.org/projeto/rua-araras-61-bairro-concordia-belo-horizonte-mg-med-car-mobile-o-medico-do-seu-carro-informacao-e-localizacao-de-servicos-automotivos-por-meio-de-app-med-car/",website:"http://app.vc/m.e.d__c.a.r"},
  {title:"LogHub",address:"Rua do Ouro, 33, Serra, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/loghub/",website:"http://www.loghub.com.br"},
  {title:"TEMPRECO",address:"Rua Manila,90, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-manila90-belo-horizonte-tempreco/",website:"http://www.tempreco.com"},
  {title:"Juris Correspondente",address:"Avenida do Contorno, 2905, Santa Efigênia, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/juris-correspondente/",website:"http://www.juriscorrespondente.com.br"},
  {title:"Newatt",address:"The Plant Coworking - R. Grão Mogol, 662 - Carmo, Belo Horizonte - MG, 30310-010",link:"http://www.sanpedrovalley.org/projeto/the-plant-coworking-r-grao-mogol-662-carmo-belo-horizonte-mg-30310-010-newatt/",website:"http://www.newatt.com.br/"},
  {title:"Wikizum",address:"Rua Paraguai 22, Novo Boa Vista - Contagem - MG",link:"http://www.sanpedrovalley.org/projeto/rua-paraguai-22-novo-boa-vista-contagem-mg-wikizum/"},
  {title:"Arkmeds",address:"Rua Jandaia 166 Belo Horizonte MG cep: 30720170",link:"http://www.sanpedrovalley.org/projeto/rua-jandaia-166-belo-horizonte-mg-cep-30720170-arkmeds/",website:"http://www.arkmeds.com"},
  {title:"I wanna sleep",address:"Rua Nossa Senhora de Lourdes n. 100 - Galpão 4 - Condomínio Flex Village Bairro Olhos D'água 30.390-530 Belo Horizonte MG Brasil",link:"http://www.sanpedrovalley.org/projeto/rua-nossa-senhora-de-lourdes-n-100-galpao-4-condominio-flex-village-bairro-olhos-dagua-30-390-530-belo-horizonte-mg-brasil-i-wanna-sleep/",website:"http://www.iwannasleep.com"},
  {title:"LinkSaúde",address:"Rua Juruá 46, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-jurua-46-belo-horizonte-linksaude/",website:"http://www.linksaude.com"},
  {title:"iEscritura – o seu Cartório de bolso.",address:"Rua Bambuí, 242, Serra, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-bambui-242-serra-belo-horizonte-iescritura-o-seu-cartorio-de-bolso/",website:"http://www.iescritura.com"},
  {title:"Conexão Obra",address:"Rua Gonçalves Dias, 1181, sala 903, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/rua-goncalves-dias-1181-sala-903-belo-horizonte-mg-conexao-obra/",website:"http://www.conexaoobra.com.br"},
  {title:"Plantão App",address:"Rua Teixeira de Freitas 800, 301 - Santo Antônio - Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-teixeira-de-freitas-800-301-santo-antonio-belo-horizonte-plantao-app/",website:"http://www.plantaoapp.com.br"},
  {title:"Lett Insights",address:"Avenida Amazonas, 5855. Bairro Gameleira, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/avenida-amazonas-5855-gameleira-belo-horizonte-mg-lett-insight/",website:"http://www.lett.com.br"},
  {title:"GameGather",address:"Rua Santa Marta 432, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-santa-marta-432-belo-horizonte-gamegather/",website:"http://www.gamegather.com.br/"},
  {title:"Samba Tech",address:"Rua Professor José Vieira de Mendonça, 770, Engenho Nogueira, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-professor-jose-vieira-de-mendonca-770-engenho-nogueira-belo-horizonte-samba-tech/",website:"http://www.sambatech.com"},
  {title:"Sumbioun",address:"Rua Roquete Mendonça, 373",link:"http://www.sanpedrovalley.org/projeto/rua-roquete-mendonca-373-sumbioun/",website:"http://sumbioun.com"},
  {title:"Home Cooker",address:"Rua Mar de Espanha, 745, CEP 30330-270 Santo Antônio, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/rua-mar-de-espanha-745-cep-30330-270-santo-antonio-belo-horizonte-mg-home-cooker/",website:"http://www.homecooker.com.br"},
  {title:"Studay",address:"Rua Jurupari, 210, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/rua-jurupari-210-belo-horizonte-mg-studay/",website:"http://www.studay.com.br"},
  {title:"Benvenuto",address:"Rua gravataí 80 Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-gravatai-80-belo-horizonte-benvenuto/",website:"http://www.benvenuto.com.br/"},
  {title:"Dribly",address:"Rua dos Goitacazes, 375, Centro, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-dos-goitacazes-375-centro-belo-horizonte-dribly/",website:"http://drib.ly"},
  {title:"Portal MatMed",address:"Rua dos Guajajaras, 628, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/rua-dos-guajajaras-628-belo-horizonte-mg-portal-matmed/",website:"http://www.portalmatmed.com.br"},
  {title:"i-Care",address:"Av Flavio dos Santos, 372, Floresta, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/av-flavio-dos-santos-372-floresta-belo-horizonte-i-care/",website:"https://www.facebook.com/appicare"},
  {title:"Start Investimentos",address:"Rua Santa Rita Durão 321 sala 1406",link:"http://www.sanpedrovalley.org/projeto/rua-santa-rita-durao-321-sala-1406-start-investimentos-2/",website:"http://startinvestimentos.com"},
  {title:"Melhor Plano",address:"Rua da Bahia, 1449 - Centro, Belo Horizonte - State of Minas Gerais, Brazil",link:"http://www.sanpedrovalley.org/projeto/rua-da-bahia-1449-centro-belo-horizonte-state-of-minas-gerais-brazil-melhor-plano/",website:"http://melhorplano.net/"},
  {title:"One Cloud",address:"Av Afonso Pena 4000, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/av-afonso-pena-4000-belo-horizonte-one-cloud/",website:"http://www.onecloudportal.com.br/"},
  {title:"PickMeApp",address:"Av. Paulo Camilo Pena, 33 - Belvedere",link:"http://www.sanpedrovalley.org/projeto/av-paulo-camilo-pena-33-belvedere-pickmeapp/",website:"http://www.pickmeapp.com.br"},
  {title:"Lince",address:"Rua dos Aimores, 462/313",link:"http://www.sanpedrovalley.org/projeto/rua-dos-aimores-462313-lince/",website:"http://www.linceapp.com.br"},
  {title:"Arte & Artefato",address:"Santa Tereza, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/santa-tereza-belo-horizonte-mg-arte-artefato/",website:"http://www.arteeartefato.com.br"},
  {title:"Price Beer",address:"Av. Contorno 6594/701 Savassi",link:"http://www.sanpedrovalley.org/projeto/av-contorno-6594701-savassi-price-beer/",website:"http://www.pricebeer.com.br"},
  {title:"EuNeném",address:"Av. Contorno 4045 Santa Efigênia Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/av-contorno-4045-santa-efigenia-belo-horizonte-eunenem/",website:"http://www.eunenem.com"},
  {title:"Where’s My Car",address:"Rua dos Tupis, 1725 - Barro Preto, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/rua-pleiades-500-santa-lucia-wheres-my-car/",website:"http://www.wheresmycar.com.br"},
  {title:"ISO4ALL",address:"Rua Senhora do Porto, 2842, Sala 14, Palmeiras, Belo Horozonte - MG",link:"http://www.sanpedrovalley.org/projeto/rua-senhora-do-porto-2842-sala-14-palmeiras-belo-horozonte-mg-iso4all/",website:"http://iso4all.com.br/"},
  {title:"Contech Software Para Restaurantes, Bares, Pizzarias",address:"Rua Antonio Dias 259, Santo Antonio. Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/rua-antonio-dias-259-santo-antonio-belo-horizonte-mg-contech-software-para-restaurantes-bares-pizzarias/",website:"http://www.programacontech.com.br"},
  {title:"Bluelux",address:"Rua Professor Manoel Pena 21, Santa Branca, Belo Horizonte, Minas Gerais",link:"http://www.sanpedrovalley.org/projeto/rua-professor-manoel-pena-21-santa-branca-belo-horizonte-minas-gerais-bluelux/",website:"http://www.bluelux.com.br"},
  {title:"Spportz",address:"Contagem, Minas Gerais",link:"http://www.sanpedrovalley.org/projeto/contagem-minas-gerais-spportz/",website:"http://www.spportz.com"},
  {title:"Flying Umbrella Studio",address:"Brasil, Minas gerais, belo horizonte",link:"http://www.sanpedrovalley.org/projeto/brasil-minas-gerais-belo-horizonte-praca-da-liberdade-flying-umbrella-studio/",website:"http://www.flyingumbrella.com.br/"},
  {title:"Me Salva",address:"Rua Viçosa, 282, sala 6, São Pedro, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-vicosa-282-sala-6-sao-pedro-belo-horizonte-me-salva/",website:"http://www.mesalvaapp.com.br"},
  {title:"Smarket",address:"Avenida do Contorno, 6434 - Savassi, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/avenida-do-contorno-6434-savassi-belo-horizonte-mg-smarket/",website:"http://www.smarket.me"},
  {title:"TestBox",address:"Rua Rio Grande do Norte, 726 Sala 304/307 Bairro Funcionários - Belo Horizonte/MG - CEP: 30130-131",link:"http://www.sanpedrovalley.org/projeto/testbox/",website:"http://www.qatest.com.br"},
  {title:"Fly – Rede de colaboração",address:"Rua Magnólia 479, Caiçaras",link:"http://www.sanpedrovalley.org/projeto/fly-rede-de-colaboracao/",website:"http://www.bhfly.com"},
  {title:"Monetizze – Produtos Digitais",address:"Rua dos Javaés, 165 - Santa Monica, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/monetizze-produtos-digitais/",website:"https://www.monetizze.com.br"},
  {title:"Méliuz",address:"Rua Jurupari, 210 - Santa Lucia, Belo Horizonte - MG, 30350-590",link:"http://www.sanpedrovalley.org/projeto/meliuz/",website:"http://www.meliuz.com.br"},
  {title:"LeadHub",address:"Av. Raja Gabaglia, 1001, Luxemburgo 30380403",link:"http://www.sanpedrovalley.org/projeto/av-raja-gabaglia-1001-luxemburgo-30380403-leadhub/",website:"http://www.leadhub.com.br"},
  {title:"QMI – Quero Meu Ingresso",address:"Rua Rafael Magalhães 164 - Santo Antônio",link:"http://www.sanpedrovalley.org/projeto/rua-rafael-magalhaes-164-santo-antonio-qmi-quero-meu-ingresso/",website:"http://www.qmi.com.br"},
  {title:"Percurso Educacional",address:"rua Alagoas, 1463, 4º andar, Funcionários, Belo Horizonte, Minas Gerais",link:"http://www.sanpedrovalley.org/projeto/rua-alagoas-1463-4o-andar-funcionarios-belo-horizonte-minas-gerais-percurso-educacional/",website:"http://www.epercurso.com.br"},
  {title:"Portal TroCar",address:"Rua Juruá, 835, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-jurua-835-belo-horizonte-portal-trocar/",website:"http://www.portaltrocar.com"},
  {title:"Reboque.Me",address:"Rua Passa Tempo, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-passa-tempo-belo-horizonte-reboque-me/",website:"http://www.reboque.me"},
  {title:"Softruck",address:"R. São Romão, 381 - Santo Antônio MG 30330-120",link:"http://www.sanpedrovalley.org/projeto/r-sao-romao-381-santo-antonio-mg-30330-120-softruck/",website:"http://www.softruck.com.br"},
  {title:"POP Recarga – O seu dinheiro para compras na Internet",address:"Rua Paraguassu, 83 - sala 503 - facePrado, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/rua-paraguassu-83-sala-503-faceprado-belo-horizonte-mg-pop-recarga-o-seu-dinheiro-para-compras-na-internet/",website:"http://www.poprecarga.com.br"},
  {title:"Risü",address:"Rua Prof. Estevão Pinto, 932, Serra, Belo Horizonte, Minas Gerais, 30210-580",link:"http://www.sanpedrovalley.org/projeto/rua-prof-estevao-pinto-932-serra-belo-horizonte-minas-gerais-30210-580-risu/",website:"http://www.risu.com.br"},
  {title:"PickMeApp",address:"Avenida Paulo Camilo Pena 33, Belvedere, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/avenida-paulo-camilo-pena-33-belvedere-belo-horizonte-pickmeapp/",website:"http://www.pickmeapp.com.br"},
  {title:"NetProject",address:"Avenida Brasil, 769, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/avenida-brasil-769-belo-horizonte-netproject/",website:"http://www.netproject.com.br"},
  {title:"Vericar",address:"Rua Jurua 46 Conj 006 Graça BH/MG",link:"http://www.sanpedrovalley.org/projeto/rua-jurua-46-conj-006-graca-bhmg-vericar/",website:"http://www.vericar.com.br"},
  {title:"Linkia",address:"Rua Buenos Aires 345 / 2º Andar, Sion",link:"http://www.sanpedrovalley.org/projeto/rua-buenos-aires-345-2o-andar-sion-linkia/",website:"http://www.linkia.com.br"},
  {title:"TicketUai",address:"Rua Senhora da Paz, 140, ap 301, Cachoerinha, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/rua-senhora-da-paz-140-ap-301-cachoerinha-belo-horizonte-ticketuai/",website:"http://www.ticketuai.com.br"},
  {title:"Mediato",address:"Alameda Ipê Branco, 338, São Luiz, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/alameda-ipe-branco-338-sao-luiz-belo-horizonte-mg-mediato/",website:"http://planearsistemas.com.br"},
  {title:"CM TECNOLOGIA",address:"Rua São Paulo, 1932 - 202 - Lourdes - Belo Horizonte / MG",link:"http://www.sanpedrovalley.org/projeto/rua-sao-paulo-1932-202-lourdes-belo-horizonte-mg-cm-tecnologia/",website:"http://www.cmtecnologia.com.br"},
  {title:"SmarttBot – S10I",address:"Rua Tomás Gonzaga 802, 2º andar, Lourdes, Belo Horizonte, MG, Brazil",link:"http://www.sanpedrovalley.org/projeto/smarttbot-s10i/",website:"https://smarttbot.com"},
  {title:"eNotas",address:"Avenida Bias Fortes 803, Belo Horizonte, Minas Gerais",link:"http://www.sanpedrovalley.org/projeto/enotas/",website:"http://www.eNotas.com.br"},
  {title:"Agora Eu Cozinho",address:"rua marechal jofre 160 nova granada belo horizonte minas gerais",link:"http://www.sanpedrovalley.org/projeto/agora-eu-cozinho/",website:"http://www.agoraeucozinho.com.br"},
  {title:"Ciclus – Conteúdo em Vídeo",address:"R. Juíz Francisco Horta, 110 - Ouro Preto",link:"http://www.sanpedrovalley.org/projeto/ciclus-conteudo-em-video/",website:"http://www.ciclusvideo.com"},
  {title:"Dito",address:"Rua Tomé de Souza 810, 7 andar, Belo Horizonte, Brasil",link:"http://www.sanpedrovalley.org/projeto/dito/",website:"http://www.dito.com.br"},
  {title:"Sympla",address:"Rua fernandes tourinho, 147, Sala 1001 - Savassi, Belo Horizonte, MG, Brasil",link:"http://www.sanpedrovalley.org/projeto/sympla/",website:"http://www.sympla.com.br/"},
  {title:"Chosen Mates",address:"Rua Carlos Alberto 198",link:"http://www.sanpedrovalley.org/projeto/rua-carlos-alberto-198-chosen-mates/",website:"http://www.chosenmates.com"},
  {title:"Bink",address:"R. Viçosa, 43 - São Pedro, Belo Horizonte - MG",link:"http://www.sanpedrovalley.org/projeto/r-vicosa-43-sao-pedro-belo-horizonte-mg-bink/",website:"http://binkapp.com/"},
  {title:"Tysdo – Things You Should Do",address:"470, Rua Fernandes Tourinho, Funcionários, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/tysdo/",website:"https://tysdoapp.com/"},
  {title:"Hekima",address:"Av. Álvares Cabral, 1315, Sala 7, Lourdes, Belo Horizonte, MG 30170-001",link:"http://www.sanpedrovalley.org/projeto/hekima/",website:"http://hekima.com/"},
  {title:"GoARTHA.com",address:"Rua Fernandes Tourinho, 1035",link:"http://www.sanpedrovalley.org/projeto/goartha-com/",website:"http://www.goartha.com"},
  {title:"Virturian",address:"Rua Grão Mogol, 662, Sion, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/virturian/",website:"http://virturian.com"},
  {title:"Esttima",address:"Av. Flávio dos Santos, 372, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/estima/"},
  {title:"StormCloud",address:"Rua da Belgica, 85, Contagem",link:"http://www.sanpedrovalley.org/projeto/stormcloud/",website:"http://www.stormcloud.me"},
  {title:"BIMMap",address:"Rua das Flôres, 85, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/bimmap/",website:"http://www.bimmap.com.br"},
  {title:"Pixla",address:"Rua Viçosa, 282, sala 6, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/pixla/",website:"http://www.pixla.com.br"},
  {title:"Pro-Treino",address:"Rua Rio Grande do Norte, 726, Sala 304/307, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/pro-treino/",website:"http://www.pro-treino.com"},
  {title:"The Card – Seu novo cartão de visita!",address:"Rua Bolívia, 178/201, bairro São Pedro, Belo Horizonte/MG",link:"http://www.sanpedrovalley.org/projeto/the-card/",website:"http://www.thecard.com.br"},
  {title:"Upstairs",address:"Rua Macapá, 267, Bairro Renascença - Belo Horizonte/Minas Gerais",link:"http://www.sanpedrovalley.org/projeto/upstairs/",website:"http://www.upstairs-app.com"},
  {title:"Aqua Multitoque",address:"R. Montevidéu, 411 - Sion Belo Horizonte - MG 30315-560",link:"http://www.sanpedrovalley.org/projeto/aqua-multitoque/",website:"http://www.aqua.com.br"},
  {title:"Learncafe",address:"Rua Teixeira de Freitas, 478, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/learncafe-2/",website:"http://www.learncafe.com/"},
  {title:"Solides Tecnologia S.A.",address:"Av Brasil, 1714, Belo Horizonte",link:"http://www.sanpedrovalley.org/projeto/profiler-educacional/",website:"http://www.solides.com.br"},
  {title:"AppProva",address:"Rua Ribeiro Junqueira, 147, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/appprova/",website:"http://www.appprova.com.br/"},
  {title:"Escola em Movimento",address:"Rua dos Inconfidentes, 1075, Funcionários, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/escola-em-movimento/",website:"http://www.escolaemmovimento.com.br/"},
  {title:"Pertoo",address:"Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/pertoo/",website:"http://www.pertoo.com"},
  {title:"Imaginie",address:"Rua dos Aimorés, 2001, Belo Horizonte, MG",link:"http://www.sanpedrovalley.org/projeto/imaginie/",website:"http://www.imaginie.com"}]) if Company.all.count == 0
